### ISSUE TITLE
Fetch event data from JSON

### ISSUE THREAD

**Issue by ythecombinator** [CocoaHeadsConference/CocoaHeadsConference.github.io#6]
Hey, great page - and I'm looking forward to the conference! 🎈 

Wouldn't it be nice to have all the event data on a `.json` file? I mean, something like:

```json
{
  "speakers":[
    {
      "name":"Francesco Perrotti",
      "photo":"images/resource/francescoperrotti.png",
      "role":"Lead Developer",
      "company":"",
      "social":{
        "linkedin":"fpg1503",
        "twitter":"fpg1503",
        "github":"fpg1503"
      }
    }
    ...
  ],
  "schedule":[
    {
      "day_type":"talks",
      "day":"03/12",
      "title":"Credenciamento & Coffee-Break",
      "thumb":"images/resource/cocoaheadsbr.png",
      "time":"8:00",
      "venue":"Área Comum",
      "short_description":"Se for seu primeiro dia, pegue seu crachá!",
      "long_description":"Aproveite esse momento para se informar sobre os workshops e demais atividades de cada sala. Converse com os participantes e tome um café."
    },
    {
      "day_type":"talks",
      "day":"03/12",
      "title":"Good Code",
      "thumb":"images/resource/francescoperrotti.png",
      "time":"10:00",
      "venue":"Auditório",
      "short_description":"O que é e como fazer!",
      "long_description":"Escrever código bom não é uma tarefa simples. Vamos abordar como reconhecer melhorias e aplicadas em nossos códigos e quais features de Swift e bibliotecas podem nos auxiliar nessa tarefa."
    }
    ...
  ],
  "sponsors":[
    {
      "name":"Mercado Livre",
      "logo":"images/sponsors/4.png",
      "website":"http://www.mercadolivre.com.br/"
    }
    ...
  ]
}
```

### Advantages

- Avoid editing markup when updating schedule or something like this - all data would be in the `.json` file.

- It would be easier to make an iOS app to fetch this data - e.g. using [Alamofire](https://github.com/Alamofire/Alamofire) + [SwiftyJSON](https://github.com/SwiftyJSON/SwiftyJSON) - like we had with [WWDC](https://itunes.apple.com/br/app/wwdc/id640199958?mt=8) one.

### Implementation

All this stuff could be easily done with an engine like [pugjs](https://pugjs.org/). Then we'd have a `compile` task which runs everytime we edit the `.json` and `deploy` one to send everything to Github Pages.

If you like the idea, I could implement and send a *Pull Request* 😄

**Comment by loloop** [comment]
Isso foi meio que resolvido no #12, acho que a issue pode ser fechada né?

**Comment by DougFischer** [comment]
Sim! :)
